server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
      # 配置nacos地址
        # server-addr: localhost:8848
        # 换成nginx的1111端口，做集群
        server-addr: 10.211.55.3:1111

# 做监控的话，要把这个全部暴露出来
management:
  endpoints:
    web:
      exposure:
        include: "*" # 注意是双引号
